// <auto-generated />
using BankingApi.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankingApi.Infrastructure.Migrations
{
    [DbContext(typeof(BankApiDbContext))]
    partial class BankApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("BankingApi.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId")
                        .HasName("PK_AccountId");

                    b.HasIndex("MemberId");

                    b.ToTable("tbl_Account");

                    b.HasData(
                        new
                        {
                            AccountId = 23456,
                            Balance = 12.5,
                            MemberId = 234789
                        });
                });

            modelBuilder.Entity("BankingApi.Domain.Entities.InstitutionEntity", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("TEXT");

                    b.HasKey("InstitutionId")
                        .HasName("PK_InsitutionId");

                    b.ToTable("tbl_Institution");

                    b.HasData(
                        new
                        {
                            InstitutionId = 78923
                        });
                });

            modelBuilder.Entity("BankingApi.Domain.Entities.MemberEntity", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId")
                        .HasName("PK_MemberId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("tbl_Member");

                    b.HasData(
                        new
                        {
                            MemberId = 234789,
                            GivenName = "John",
                            InstitutionId = 78923,
                            Surname = "Doe"
                        });
                });

            modelBuilder.Entity("BankingApi.Domain.Entities.AccountEntity", b =>
                {
                    b.HasOne("BankingApi.Domain.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BankingApi.Domain.Entities.MemberEntity", b =>
                {
                    b.HasOne("BankingApi.Domain.Entities.InstitutionEntity", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });
#pragma warning restore 612, 618
        }
    }
}
